/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as JoinRouteImport } from './routes/join'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupsAllRouteImport } from './routes/groups/all'
import { Route as GroupCreateNewRouteImport } from './routes/group/create/new'
import { Route as GroupGroupIDMembersRouteImport } from './routes/group/$groupID/members'
import { Route as GroupGroupIDDetailsRouteImport } from './routes/group/$groupID/details'
import { Route as GroupGroupIDCreateExpenseRouteImport } from './routes/group/$groupID/create-expense'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsAllRoute = GroupsAllRouteImport.update({
  id: '/groups/all',
  path: '/groups/all',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupCreateNewRoute = GroupCreateNewRouteImport.update({
  id: '/group/create/new',
  path: '/group/create/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupGroupIDMembersRoute = GroupGroupIDMembersRouteImport.update({
  id: '/group/$groupID/members',
  path: '/group/$groupID/members',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupGroupIDDetailsRoute = GroupGroupIDDetailsRouteImport.update({
  id: '/group/$groupID/details',
  path: '/group/$groupID/details',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupGroupIDCreateExpenseRoute =
  GroupGroupIDCreateExpenseRouteImport.update({
    id: '/group/$groupID/create-expense',
    path: '/group/$groupID/create-expense',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/profile': typeof ProfileRoute
  '/groups/all': typeof GroupsAllRoute
  '/group/$groupID/create-expense': typeof GroupGroupIDCreateExpenseRoute
  '/group/$groupID/details': typeof GroupGroupIDDetailsRoute
  '/group/$groupID/members': typeof GroupGroupIDMembersRoute
  '/group/create/new': typeof GroupCreateNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/profile': typeof ProfileRoute
  '/groups/all': typeof GroupsAllRoute
  '/group/$groupID/create-expense': typeof GroupGroupIDCreateExpenseRoute
  '/group/$groupID/details': typeof GroupGroupIDDetailsRoute
  '/group/$groupID/members': typeof GroupGroupIDMembersRoute
  '/group/create/new': typeof GroupCreateNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/profile': typeof ProfileRoute
  '/groups/all': typeof GroupsAllRoute
  '/group/$groupID/create-expense': typeof GroupGroupIDCreateExpenseRoute
  '/group/$groupID/details': typeof GroupGroupIDDetailsRoute
  '/group/$groupID/members': typeof GroupGroupIDMembersRoute
  '/group/create/new': typeof GroupCreateNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/join'
    | '/profile'
    | '/groups/all'
    | '/group/$groupID/create-expense'
    | '/group/$groupID/details'
    | '/group/$groupID/members'
    | '/group/create/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/join'
    | '/profile'
    | '/groups/all'
    | '/group/$groupID/create-expense'
    | '/group/$groupID/details'
    | '/group/$groupID/members'
    | '/group/create/new'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/join'
    | '/profile'
    | '/groups/all'
    | '/group/$groupID/create-expense'
    | '/group/$groupID/details'
    | '/group/$groupID/members'
    | '/group/create/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  JoinRoute: typeof JoinRoute
  ProfileRoute: typeof ProfileRoute
  GroupsAllRoute: typeof GroupsAllRoute
  GroupGroupIDCreateExpenseRoute: typeof GroupGroupIDCreateExpenseRoute
  GroupGroupIDDetailsRoute: typeof GroupGroupIDDetailsRoute
  GroupGroupIDMembersRoute: typeof GroupGroupIDMembersRoute
  GroupCreateNewRoute: typeof GroupCreateNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/all': {
      id: '/groups/all'
      path: '/groups/all'
      fullPath: '/groups/all'
      preLoaderRoute: typeof GroupsAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/create/new': {
      id: '/group/create/new'
      path: '/group/create/new'
      fullPath: '/group/create/new'
      preLoaderRoute: typeof GroupCreateNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$groupID/members': {
      id: '/group/$groupID/members'
      path: '/group/$groupID/members'
      fullPath: '/group/$groupID/members'
      preLoaderRoute: typeof GroupGroupIDMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$groupID/details': {
      id: '/group/$groupID/details'
      path: '/group/$groupID/details'
      fullPath: '/group/$groupID/details'
      preLoaderRoute: typeof GroupGroupIDDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$groupID/create-expense': {
      id: '/group/$groupID/create-expense'
      path: '/group/$groupID/create-expense'
      fullPath: '/group/$groupID/create-expense'
      preLoaderRoute: typeof GroupGroupIDCreateExpenseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  JoinRoute: JoinRoute,
  ProfileRoute: ProfileRoute,
  GroupsAllRoute: GroupsAllRoute,
  GroupGroupIDCreateExpenseRoute: GroupGroupIDCreateExpenseRoute,
  GroupGroupIDDetailsRoute: GroupGroupIDDetailsRoute,
  GroupGroupIDMembersRoute: GroupGroupIDMembersRoute,
  GroupCreateNewRoute: GroupCreateNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
